### ISSUE TITLE
Apply fortitude linting to .pf files

### ISSUE THREAD

**Issue by connoraird** [UCL-ARC/fortran-tooling#54]
### Definition of Done / Acceptance Criteria

All files within our repo should be formatted with fortitude.
- [ ] The .pf files for pFUnit tests are linted with fortitude and pre-commit
- [ ] Any linting issues are resolved

### Comments

Can be done via 
```toml
[check]
file-extensions = ["pf","f90"]
ignore = [
    "C003", # 'implicit none' missing 'external'.
    "S091", # file extension should be '.f90' or '.F90'. Disabled to allow formatting of pFUnit files.
]
line-length = 132
respect-gitignore = false

[check.per-file-ignores]
"**.pf" = ["E001"] # Ignore syntax errors in .pf files as annotations cause false positives

```
